### PR TITLE
Changed bikeshedding URL to use a diff online url

### PR DESCRIPTION
**Pull request by danquack**

### CODE REVIEW

**Comment by danquack** [comment]
@jjasghar this is a pretty cool app. Any chance you still maintain this?

**Comment by jjasghar** [comment]
Not really, it just did it's job back in the day. Would you like to start maintaining it?

**Comment by danquack** [comment]
I wouldn’t mind maintaining this.

**Comment by jjasghar** [comment]
You got it! Thanks for stepping up. :metal:

**Comment by danquack** [comment]
@jjasghar - where does the npm rights come?

**Comment by jjasghar** [comment]
oh! opps, what's your npm name?

**Comment by danquack** [comment]
dan_quack

**Comment by jjasghar** [comment]
you should be good now!

**Pull request merged**
